### ISSUE TITLE
No implementation of method: :named of protocol: #'somnium.congomongo/StringNamed

### ISSUE THREAD

**Issue by holtzermann17** [zk/clojuredocs#113]
I encounter this error when I run `foreman start -f Procfile.dev`.

```
18:45:50 web.1   | Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :named of protocol: #'somnium.congomongo/StringNamed found for class: nil, compiling:(/tmp/form-init3247650463222747370.clj:1:72)
18:45:50 web.1   | 	at clojure.lang.Compiler.load(Compiler.java:7142)
18:45:50 web.1   | 	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
18:45:50 web.1   | 	at clojure.main$load_script.invoke(main.clj:274)
18:45:50 web.1   | 	at clojure.main$init_opt.invoke(main.clj:279)
18:45:50 web.1   | 	at clojure.main$initialize.invoke(main.clj:307)
18:45:50 web.1   | 	at clojure.main$null_opt.invoke(main.clj:342)
18:45:50 web.1   | 	at clojure.main$main.doInvoke(main.clj:420)
18:45:50 web.1   | 	at clojure.lang.RestFn.invoke(RestFn.java:421)
18:45:50 web.1   | 	at clojure.lang.Var.invoke(Var.java:383)
18:45:50 web.1   | 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
18:45:50 web.1   | 	at clojure.lang.Var.applyTo(Var.java:700)
18:45:50 web.1   | 	at clojure.main.main(main.java:37)
18:45:50 web.1   | Caused by: java.lang.IllegalArgumentException: No implementation of method: :named of protocol: #'somnium.congomongo/StringNamed found for class: nil
18:45:50 web.1   | 	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
18:45:50 web.1   | 	at somnium.congomongo$eval12502$fn__12503$G__12493__12508.invoke(congomongo.clj:36)
18:45:50 web.1   | 	at somnium.congomongo$make_connection.doInvoke(congomongo.clj:135)
18:45:50 web.1   | 	at clojure.lang.RestFn.invoke(RestFn.java:423)
18:45:50 web.1   | 	at somnium.congomongo$make_connection.invoke(congomongo.clj:133)
18:45:50 web.1   | 	at clojuredocs.main$start.invoke(main.clj:66)
18:45:50 web.1   | 	at user$eval26115.invoke(form-init3247650463222747370.clj:1)
18:45:50 web.1   | 	at clojure.lang.Compiler.eval(Compiler.java:6703)
18:45:50 web.1   | 	at clojure.lang.Compiler.eval(Compiler.java:6693)
18:45:50 web.1   | 	at clojure.lang.Compiler.eval(Compiler.java:6693)
18:45:50 web.1   | 	at clojure.lang.Compiler.eval(Compiler.java:6692)
18:45:50 web.1   | 	at clojure.lang.Compiler.load(Compiler.java:7130)
```

**Comment by zk** [comment]
@holtzermann17 looking into this now

**Comment by zk** [comment]
@holtzermann17 can't seem to repro, can you try a `lein clean` then `bin/dev`?

**Comment by zk** [comment]
Closing, please reopen if you have further info.

**Comment by holtzermann17** [comment]
:+1: 

I couldn't reproduce it either, and things are working now...

**Comment by zk** [comment]
Great, thanks Joe

**Comment by holtzermann17** [comment]
Er sorry bad news, things were working briefly and then crashed with the same error.  I was able to visit http://localhost:5000/ and the Clojuredocs "homepage" was there, then I saw the same error as before print out.  Here's a [somewhat more detailed print out](https://gist.github.com/holtzermann17/d174aba9292335a27289#file-gistfile1-txt-L213).

**Comment by holtzermann17** [comment]
And here is the temporary file that it mentions as the source of the error. https://gist.githubusercontent.com/holtzermann17/de4ee626fe951082a07d/raw/af34c526991acb6d475e627ef1d2be8ba9c75a60/gistfile1.clj

I'll try to be more attentive to messages here if I can help debug this.

**Comment by zk** [comment]
@holtzermann17 Looks like you're on a linux distro?

**Comment by holtzermann17** [comment]
yes, it's Ubuntu 14.10.

**Comment by zk** [comment]
Great, I'll see if I can repro on that.

**Comment by zk** [comment]
Prob not going to get to this any time soon, reopen if somebody else wants to pick it up.
