### ISSUE TITLE
lein repl error - Unable to resolve symbol: do

### ISSUE THREAD

**Issue by ilyabe** [zk/clojuredocs#201]
I can't seem to run the project locally, on my Mac, with Leiningen 2.8.1 on Java 1.8.0_192.

1. I clone the repo
2. Install the [reqs](https://github.com/zk/clojuredocs#reqs)
3. Run `bin/dev` and get this error
```clojure
WARNING!!! version ranges found for:
[nsfw "0.12.29" :exclusions [org.clojure/core.async org.clojure/clojurescript]] -> [clj-aws-s3 "0.3.10"] -> [com.amazonaws/aws-java-sdk "1.7.5"] -> [joda-time "[2.2,)"]
Consider using [nsfw "0.12.29" :exclusions [joda-time org.clojure/clojurescript org.clojure/core.async]].

Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: do in this context, compiling:(/private/var/folders/27/wxx9_rgd14z0cyhq3gt295q48zlqn5/T/form-init4583735242224188444.clj:1:1050)
	at clojure.lang.Compiler.analyze(Compiler.java:6792)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.eval(Compiler.java:7059)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: do in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:7299)
	at clojure.lang.Compiler.resolve(Compiler.java:7243)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7204)
	at clojure.lang.Compiler.analyze(Compiler.java:6752)
	... 27 more
```
Looks like it's specifically starting the `repl` that fails because if I run `lein repl :headless` then I get the same error. It also looks like it's related to the `:repl-options` because if I remove this line in the `project.clj` 
```clojure
:repl-options {:init (load-file "reup.clj")}
```
then `lein repl` starts OK. What am I doing wrong?

**Comment by ilyabe** [comment]
I think it has to do with this line of code

https://github.com/zk/clojuredocs/blob/master/reup.clj#L1

and that `in-ns`does not load `clojure.core`, as documented here

http://clojuredocs.org/clojure.core/in-ns

If I change it to do `(ns user)` instead then it works, but then I wonder how this works on other folks machines? Maybe something setup in the environment that I don't have?

**Comment by ilyabe** [comment]
Nope, not that either. I just had a problem in my `profiles.clj`.

**Comment by zk** [comment]
Hi Ilya, I'm curious, what was solution?

**Comment by ilyabe** [comment]
In my `profiles.clj` I had something like this
```clojure
{:user {:repl-options {:init (do (set! *print-length* 100))}}}
```
and that's the `do` it was tripping on. I'm not sure why this itself is a problem, I simply removed it for now. Interestingly, this didn't cause a problem in projects that didn't have their own `:repl-options`.
